# Generated by Django 5.0.1 on 2025-11-10 23:19

import apps.products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirAmbience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_type', models.CharField(choices=[('humidifier', 'Humidifier'), ('diffuser', 'Diffuser'), ('essential_oil', 'Essential Oil'), ('room_spray', 'Room Spray'), ('car_freshener', 'Car Freshener'), ('candle', 'Scented Candle')], max_length=20)),
                ('scent_notes', models.TextField(blank=True, help_text='Fragrance notes and description')),
                ('size_options', models.CharField(default='50ml', help_text='Available sizes', max_length=100)),
                ('usage_instructions', models.TextField(blank=True, help_text='How to use the product')),
                ('features', models.TextField(blank=True, help_text='Key features and benefits')),
                ('coverage_area', models.CharField(blank=True, help_text='e.g., Up to 500 sq ft', max_length=100)),
                ('duration', models.CharField(blank=True, help_text='e.g., Lasts 30 days', max_length=100)),
                ('image', models.ImageField(upload_to='air_ambience/', validators=[apps.products.validators.validate_image_file_extension, apps.products.validators.validate_image_file_size])),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Air Ambience Product',
                'verbose_name_plural': 'Air Ambience Products',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
