# Generated by Django 5.0.1 on 2025-11-10 23:25

import apps.products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_airambience'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfumeOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concentration', models.CharField(choices=[('pure_oil', 'Pure Oil'), ('oil_blend', 'Oil Blend'), ('concentrated', 'Concentrated')], default='pure_oil', max_length=20)),
                ('size_options', models.CharField(default='10ml', help_text='Available sizes (e.g., 10ml, 15ml)', max_length=100)),
                ('longevity', models.CharField(choices=[('4-8 hours', '4-8 hours'), ('8-12 hours', '8-12 hours'), ('12-16 hours', '12-16 hours'), ('16-24 hours', '16-24 hours'), ('24+ hours', '24+ hours')], default='8-12 hours', max_length=20)),
                ('top_notes', models.CharField(blank=True, help_text='Top notes (comma separated)', max_length=200)),
                ('middle_notes', models.CharField(blank=True, help_text='Middle notes (comma separated)', max_length=200)),
                ('base_notes', models.CharField(blank=True, help_text='Base notes (comma separated)', max_length=200)),
                ('scent_family', models.CharField(blank=True, help_text='e.g., Woody, Floral, Oriental', max_length=100)),
                ('application_tips', models.TextField(blank=True, help_text='How to apply and use')),
                ('ingredients', models.TextField(blank=True, help_text='Key ingredients and benefits')),
                ('image', models.ImageField(upload_to='perfume_oils/', validators=[apps.products.validators.validate_image_file_extension, apps.products.validators.validate_image_file_size])),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_custom_blend', models.BooleanField(default=False, help_text='Available for custom blending')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfume Oil',
                'verbose_name_plural': 'Perfume Oils',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
