# Generated by Django 5.0.1 on 2025-11-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_perfumeoil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airambience',
            name='image',
        ),
        migrations.RemoveField(
            model_name='dupeproduct',
            name='image',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='image',
        ),
        migrations.RemoveField(
            model_name='perfumeoil',
            name='image',
        ),
        migrations.AddField(
            model_name='airambience',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/300x300?text=Air+Ambience', help_text='URL of the air ambience product image', max_length=500),
        ),
        migrations.AddField(
            model_name='dupeproduct',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/300x300?text=Dupe+Product', help_text='URL of the dupe product image', max_length=500),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/400x300?text=Gallery+Image', help_text='URL of the gallery image', max_length=500),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the gift card image', max_length=500),
        ),
        migrations.AddField(
            model_name='perfumeoil',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/300x300?text=Perfume+Oil', help_text='URL of the perfume oil image', max_length=500),
        ),
    ]
