# Generated by Django 5.0.1 on 2025-11-17 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_airambience_image_remove_dupeproduct_image_and_more'),
        ('products', '0006_remove_productimage_image_productimage_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dupeproduct',
            name='product',
            field=models.OneToOneField(blank=True, help_text='Link to the actual product in inventory', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dupe_info', to='products.product'),
        ),
    ]
