# Generated by Django 5.0.1 on 2025-11-17 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_dupeproduct_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dupeproduct',
            name='product',
        ),
    ]
