# Generated by Django 5.0.1 on 2026-01-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_dupeproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='airambience',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload image from your computer', null=True, upload_to='air_ambience/'),
        ),
        migrations.AddField(
            model_name='dupeproduct',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload image from your computer', null=True, upload_to='dupes/'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload image from your computer', null=True, upload_to='gallery/'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload image from your computer', null=True, upload_to='giftcards/'),
        ),
        migrations.AddField(
            model_name='perfumeoil',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload image from your computer', null=True, upload_to='perfume_oils/'),
        ),
        migrations.AlterField(
            model_name='airambience',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the air ambience product image (e.g., from CDN or external source)', max_length=500),
        ),
        migrations.AlterField(
            model_name='dupeproduct',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the dupe product image (e.g., from CDN or external source)', max_length=500),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the gallery image (e.g., from CDN or external source)', max_length=500),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the gift card image (e.g., from CDN or external source)', max_length=500),
        ),
        migrations.AlterField(
            model_name='perfumeoil',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the perfume oil image (e.g., from CDN or external source)', max_length=500),
        ),
    ]
