# Generated by Django 5.0.1 on 2026-01-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_airambience_image_file_dupeproduct_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dupeproduct',
            name='designer_image_file',
            field=models.ImageField(blank=True, help_text='Upload designer fragrance image from your computer', null=True, upload_to='designer_fragrances/'),
        ),
        migrations.AddField(
            model_name='dupeproduct',
            name='designer_image_url',
            field=models.URLField(blank=True, help_text='URL of the designer fragrance image (e.g., from CDN or external source)', max_length=500),
        ),
    ]
