# Generated by Django 5.0.1 on 2025-11-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_limited_edition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('perfume', 'Perfume'), ('perfume_oil', 'Perfume Oil'), ('air_ambience', 'Air Ambience')], default='perfume', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='scent_family',
            field=models.CharField(blank=True, choices=[('floral', 'Floral'), ('woody', 'Woody'), ('citrus', 'Citrus'), ('oriental', 'Oriental'), ('fresh', 'Fresh'), ('spicy', 'Spicy')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='scent_notes',
            field=models.TextField(blank=True, help_text='Top, middle, and base notes'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_options',
            field=models.CharField(default='50ml', help_text='Available sizes (e.g., 50ml, 100ml)', max_length=100),
        ),
    ]
