# Generated by Django 5.0.1 on 2025-11-10 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_limited_edition_product_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_dupe',
            field=models.BooleanField(default=False, help_text='Is this product a dupe of a luxury fragrance?'),
        ),
        migrations.AddField(
            model_name='product',
            name='original_perfume',
            field=models.ForeignKey(blank=True, help_text='The original luxury perfume this product is a dupe of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dupes', to='products.product'),
        ),
    ]
