# Generated by Django 5.0.1 on 2025-11-10 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_dupe_product_original_perfume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_dupe',
        ),
        migrations.RemoveField(
            model_name='product',
            name='original_perfume',
        ),
    ]
