# Generated by Django 5.0.1 on 2025-11-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_is_dupe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/300x300?text=No+Image', help_text='URL of the product image (e.g., from CDN, cloud storage, or external source)', max_length=500),
        ),
    ]
