# Generated by Django 5.0.1 on 2026-01-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='category_slug_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_slug_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_cat_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_featured_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_price_idx',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image file (will be stored in Railway bucket)', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or provide external image URL', max_length=500),
        ),
    ]
