# Generated by Django 5.0.1 on 2026-01-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_category_category_slug_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload image from your computer', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the product image (e.g., from CDN or external source)', max_length=500),
        ),
    ]
