# Generated by Django 5.0.1 on 2026-01-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productimage_image_productimage_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload category image from your computer', null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the category image (e.g., from CDN or external source)', max_length=500),
        ),
    ]
