# Generated by Django 5.0.1 on 2025-11-04 08:32

import apps.products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', validators=[apps.products.validators.validate_image_file_extension, apps.products.validators.validate_image_file_size]),
        ),
    ]
