# Generated by Django 5.0.1 on 2025-11-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='URL of the blog post featured image', max_length=500),
        ),
    ]
