# Generated by Django 5.0.1 on 2026-01-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogpost_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_file',
            field=models.ImageField(blank=True, help_text='Upload featured image from your computer', null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='URL of the blog post featured image (e.g., from CDN or external source)', max_length=500),
        ),
    ]
